### ISSUE TITLE
Glass shards...

### ISSUE THREAD

**Issue by johnRedden** [johnRedden/iThrowRock#11]
We first need a green glass shard png... then try to code up a particle explosion it.  Shards drop under gravity and disappear after a bit.

**Comment by mecharmor** [comment]
Ok.
I will Photoshop that tonight.

----- Reply message -----

**Comment by johnRedden** [comment]
4 new bottle shards look good (in the NEW IMAGES FOR TESTING) folder.  Paul you can copy these images into the asset folder and spritebatch them in the code.

**Comment by johnRedden** [comment]
Should add random directions for shards needed.

**Comment by johnRedden** [comment]
Green bottle shards is working.
