### ISSUE TITLE
new sprites 

### ISSUE THREAD

**Issue by mecharmor** [johnRedden/iThrowRock#15]
The game needs a Golden Bottle spritesheet added in and animated.
and the molotov cocktail spritesheet added
and the dark bottle spritesheet added

**Comment by johnRedden** [comment]
Moltov animation added AND Dark bottle animation added.

I think there will ever only be one golden bottle...  it should randomly go by only rarely.    Not sure how to do this yet.

**Comment by pgonzbecer** [comment]
In retrospect, I shouldn't have made the golden bottle into a group. It is now a single item and has a 4% chance of spawning for each time you break a bottle, but doesn't spawn if you are already in thrasher mode
