### ISSUE TITLE
Ghost rock...

### ISSUE THREAD

**Issue by johnRedden** [johnRedden/iThrowRock#16]
Isabel had a good idea for a ghost rock flying off after the real rock hits a molotov.  Also, some art for lives is needed... maybe two frames... blank and filled.  

I like skulls: https://commons.wikimedia.org/wiki/Category:Human_skulls_in_art

**Comment by mecharmor** [comment]
Ghost rock is created

**Comment by pgonzbecer** [comment]
All rocks go to heaven.
Although new issue that ties in with this. 

@mecharmor If you can, can you make the death sprite sheet not have opacity? I coded it up so it can tinker with the <strike>capacity</strike> opacity, but anything more than 4 fps on the animation makes it look glitchy

**Comment by johnRedden** [comment]
The ghost rock looks absolutely great!  I think Isabel gets the credit on that... that idea makes it.

**Comment by mecharmor** [comment]
Yah Isabel definitely gets credit for that one.We might have to get licensing permission from her or we might get sued.  Lol Jk.

----- Reply message -----

**Comment by mecharmor** [comment]
the ghost rock has its rotation set to what the original rock was.  it needs to stay verticle every time.  otherwise you have an angel rock flying sideways.

**Comment by johnRedden** [comment]
actually, I like it a bit cocked.  Looks cool.

**Comment by pgonzbecer** [comment]
Tilt got fixed
