### ISSUE TITLE
Game overlay menu

### ISSUE THREAD

**Issue by johnRedden** [johnRedden/iThrowRock#18]
The game overlay should have at least.
1. Main menu - to toggle sound.  Score and level should be maintained.
2. Reset game - to start over... scores and levels all reset.

Or maybe...
1. Quit - send to main menu
2. Toggle music
3. Toggle sound

I wonder if phaser has a pause function built in?  We could add that to the menu too

**Comment by johnRedden** [comment]
Here is how to pause... super easy:  game.paused = true;

http://phaser.io/examples/v2/misc/pause-menu

##

**Comment by mecharmor** [comment]
i made a pause button spritesheet. i will add it in the asset's folder after class tonight.

**Comment by johnRedden** [comment]
I did some work on the game menu overlay.  Need some better art for the buttons.  I do like the writing on the wood...  maybe just an old wood plank no border with white letters?    Also, I wonder if we could do better than the sandwich icon?

Also, this.game.paused = true; works but it pauses the whole game... even the buttons.  So not good.

Functionality is still not done.  It's a holiday!

**Comment by mecharmor** [comment]
I was thinking the same thing with the sandwich icon... im still not sure what we could change it out with tho.  maybe a pause icon??  so if you click the pause icon then the overlay slides down and the game pauses.  and maybe when the game is un-paused then there could be a 3 sec timer so the user has time to setup before the game starts playing again?  idk.  Have a nice thanksgiving

**Comment by johnRedden** [comment]
The game overlay now completely works... i think?  Just add better art.
