### ISSUE TITLE
Game Over?

### ISSUE THREAD

**Issue by pgonzbecer** [johnRedden/iThrowRock#19]
Err, So there is a function that gets called when it detects a game over... But where should it go? Title screen or restarts you to a fresh new game?

**Comment by johnRedden** [comment]
Maybe a "game over" overlay... then push a button to play again and it resets back to level 1?

**Comment by mecharmor** [comment]
there is a Play Button and a reset button in the new images folder.  i can change them out with something different if you guys want.

**Comment by johnRedden** [comment]
Goal for today is to figure out how to die?  I can't seem to get pause to work either.  I am thinking an overlay that says:

Game Over!
[ Play Again ]
[ Main Menu ]

Reset all scores and stuff.  BTW... this game is kinda fun!

**Comment by mecharmor** [comment]
That over lay sounds good.I will try to make buttons of some sort.
Also is there any way to blur the background/game when the overlay pops up?

----- Reply message -----

**Comment by johnRedden** [comment]
Game over should trigger the game overlay button?

**Comment by mecharmor** [comment]
game over or when you beat the level.  or something like that.   i just quickly photoshopped that overlay just for a visual idea of what i was thinking an overlay might look like.

**Comment by johnRedden** [comment]
Done.  Went fast... this is pretty simple. We can make the overlay more fancy as time permits.
