### ISSUE TITLE
About State

### ISSUE THREAD

**Issue by johnRedden** [johnRedden/iThrowRock#24]
I added a new about state... needs better buttons and some way to scroll.  How to scroll in phaser?

I put the assets in the menu folder.

**Comment by johnRedden** [comment]
Got scrolling... used the following phaser plugin.  It just works!

http://jdnichollsc.github.io/Phaser-Kinetic-Scrolling-Plugin/

Nice.

**Comment by mecharmor** [comment]
This laptop is on sale pretty cheap on newegg: Shell Shocker Deal. Exclusive Jaw Dropping Savings on PC Components and Electronics - Newegg.com

|   |
|   |  |   |   |   |   |   |
| Shell Shocker Deal. Exclusive Jaw Dropping Savings on PC...Newegg Shell Shocker is exclusive daily deal on PC components or Electronics. Once you know, you Newegg! |
|  |
| View on www.newegg.com | Preview by Yahoo |
|  |
|   |

it has a video card so it has more power than the average laptop
