### ISSUE TITLE
Level Scores

### ISSUE THREAD

**Issue by johnRedden** [johnRedden/iThrowRock#25]
The levels should be related to the score somehow.  Higher level the more points you get for green bottles.  (Incentive to level up).

**Comment by pgonzbecer** [comment]
It does already, although I think the change is a little too subtle to notice

> increaseScore((10 + 2 \* (BasicGame.level-1)) \* this.combo)     @ bottleHit2 func

Which for each level increases the score by 2. So level 1= 10pts, 2= 12pts, 3= 14pt ...

**Comment by johnRedden** [comment]
Ok, missed that.

**Comment by johnRedden** [comment]
Hooked up BasicGame.highLevel
