### ISSUE TITLE
Pause Button is Ugly

### ISSUE THREAD

**Issue by johnRedden** [johnRedden/iThrowRock#26]
I'm just sayin'.  Also, we might consider redesigning the big play button in the main menu?

**Comment by mecharmor** [comment]
I definitely want to change interface stuff. I'm just trying to figure out what to change it out with

----- Reply message -----

**Comment by johnRedden** [comment]
I animated the awesome new lever... the actual lever is a bit long but I think it look good.  Have a look.  I am closing this issue.
