### ISSUE TITLE
Instruction?

### ISSUE THREAD

**Issue by johnRedden** [johnRedden/iThrowRock#29]
A reviewer said there should be instructions?  I guess we should give instructions.  

"Throw rock - hit stuff."

??

**Comment by mecharmor** [comment]
Oh yeah. Instructions would be handy. I will need to work on that a bit.

Sent from my Sprint phone.

----- Reply message -----

**Comment by johnRedden** [comment]
The about menu is done... I think the hanging options like that looks good.  Fill in your blanks.

**Comment by johnRedden** [comment]
I think the menu looks good.
