### ISSUE TITLE
Play Button

### ISSUE THREAD

**Issue by johnRedden** [johnRedden/iThrowRock#3]
Need a nice play button for the main menu.  Here is how they work:

http://phaser.io/examples/v2/buttons/action-on-click

For now I just used the bottle...

**Comment by ZaCkOX** [comment]
Hi John, if you could direct me how to make changes, I downloaded the zip file of our project, pulled out the contents into a single folder but couldn't figure out how to tie it all together with visual studio. I was able to open the files independently but that seems frustrating. If I make changes to game.js how would I view those changes? I could only see the file I opened. I guess I could copy over to cloud9 but I assume the reason we don't want to do that is sharing it there. I'm ready to work on this, I just need to figure out how to start.

Zachary Stafford

**Comment by johnRedden** [comment]
Yeah, there are two things going on... 1. Setting up and working with
gitHub.  2. Setting up and working with Visual Studio.

Both a bit frustrating.  But once you figure it out these are awesome tools.

Visual Studio:
1. File >> Open >> Website
2. Navigate to the extracted folder (probably name iThrowRock-master.)
3. It should load in nicely.  Click on index.html in the Solution Explorer
(inside VS).
4. Click Run in the toolbar
[image: Inline image 1]
And it should run in chrome or whatever you pick.

For GitHub... Ugh

**Comment by johnRedden** [comment]
For gitHub do you plan on using the windows program they provide?  The
desktop client?

https://desktop.github.com/

It makes syncing your changes easier and you will not have to download the
zipped file every time.
