### ISSUE TITLE
Glitch unable to reproduce

### ISSUE THREAD

**Issue by johnRedden** [johnRedden/iThrowRock#32]
Ok, a kid was stuck in thrasher mode... but the background was normal color.  Unable to reproduce this situation since.

**Comment by pgonzbecer** [comment]
Not enough information, how was he/she stuck in thrasher mode?

**Comment by johnRedden** [comment]
Not sure.  Also, Cory got a crash when two bottles were simultaneously
broken on death.  I have see that before too. We need to follow the death
sequence of events.

**Comment by pgonzbecer** [comment]
I couldn't replicate Cory's crash, even tweaking the parameters for the bottles to have everything the same. The only thing I found was that it had a significant lag when multiple bottles were broken...

**Comment by pgonzbecer** [comment]
Yeah I think Cory's crash might have been P2 Physics doing too much at once?

**Comment by johnRedden** [comment]
Gremlins!  I will be back in the game tomorrow after I finish grading today.
