### ISSUE TITLE
Menu Overlay

### ISSUE THREAD

**Issue by johnRedden** [johnRedden/iThrowRock#6]
I added a game menu overlay (HIT REFRESH) when playing it... now need to make it less cumbersome and more visually appealing.  The images(buttons) are white (from some tutorial I looked at) and so I had to change the background color to see it.

I was thinking the rock should bounce off of the menu button but I could not figure out how to get a button to respond to p2 physics.

**Comment by pgonzbecer** [comment]
Less cumbersome because it is out of the touch zone, but don't know if it is visually appealing

**Comment by johnRedden** [comment]
Looks better at the top for sure.

**Comment by johnRedden** [comment]
I think its in a good place... unless somebody has a better idea I am closing this issue.
