### ISSUE TITLE
Refresh Not working

### ISSUE THREAD

**Issue by johnRedden** [johnRedden/iThrowRock#7]
I am having trouble getting the browser to refresh on the rawgit cdn link... anyone else?  The current version should look like this:
https://s3-us-west-1.amazonaws.com/www.edunetsystems.com/games/iThrowRock/index.html

**Comment by mecharmor** [comment]
It's working for me.maybe try Firefox.
Ad blockers will stop the game from working and maybe your browser cached some of the old game and was giving you issues??

----- Reply message -----

**Comment by johnRedden** [comment]
Do not trust that cdn link...!!
